input_imgs_dir: "/home/gkf/Inpaint-Anything/data/xinye5-Scene-002.mp4.frames"
point_coords: [0.5, 0.7]
text_prompt: "sit on an outdoor bench"
dilate_kernel_size: 5
seed: null
sample_rate: 4
use_cf_attn: False